# Plugins
plugins:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']

collections:
  - members

# Site Settings
title: "TR7"
email: "devfest@gdg.org.ua"
description: "TR7 is a cybersecurity company located in Ankara"
baseurl: ""
url: "https://gdg-x.github.io"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-43643469-5"
googleAnalyticsSiteUrl: "gdg-x.github.io"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no" 

# Organizer Info
organizerName: "GDG Lviv"
organizerAlternateName: "Google Developer Group Lviv"
organizerDescription: "Open and volunteer geek communities who create exciting projects and share experience about Google technology with passion."
organizerEmail: "lviv@gdg.org.ua"
organizerLogo: "/img/seo/logo3.png"
organizerLink: "http://lviv.gdg.org.ua/"

# Head
metaKeywords: "event, gdg, devfest, google, programming, android, chrome, developers, lviv"
twitterAccount: "@DevFest"
socialImageSrcGooglePlus: "/img/seo/logo3.png"
socialImageSrcTwitter: "/img/seo/logo3.png"
socialImageSrcFacebook: "/img/seo/logo3.png"

# Documents
c4pUrl: "https://bit.ly/dfua-c4p"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 - {permalink: "/about/", text: "About"}
 - {permalink: "/solutions/", text: "Solutions & Products"}
 - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/documentation/", text: "Documentation"}
 - {permalink: "/references/", text: "References"}
 - {permalink: "/contact/", text: "Contact Us"}
 - {permalink: "/tr/", text: "TR"}
 - {permalink: "/", text: "EN"}


# TR Navigation
tr_navigationLinks:
 - {permalink: "/tr/", text: "Anasayfa"}
 - {permalink: "/tr/hakkimizda/", text: "Hakkımızda"}
 - {permalink: "/tr/cozumler/", text: "Çözümler & Ürünler"}
 - {permalink: "/tr/blog/", text: "Blog"}
 - {permalink: "/tr/dokumantasyon/", text: "Dokümantasyon"}
 - {permalink: "/tr/referanslar/", text: "Referanslar"}
 - {permalink: "/tr/iletisim/", text: "İletİşİm"}
 - {permalink: "/tr/", text: "TR"}
 - {permalink: "/", text: "EN"}


bottomNavigationLinks:
 - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}
rightNavigationButtons:
 - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}

# Hero Block
heroImage: "bg_image.jpg"
heroTitle: "TR7 <typeout> Application Security Platform"
trHeroTitle: "TR7 <typeout> Uygulama Güvenlik Platformu"
eventDate: "TR7 Load Balancing and Web Application Firewall"
trEventDate: "TR7 Yük Dengeleme ve Uygulama Güvenlik Platformu"
typeoutTextValues: '"", "Load Balancing", "Application Security", "WAF", "DDoS Protection"'
trTypeoutTextValues: '"", "Yük Dengeleme", "Uygulama Güvenliği", "WAF", "DDoS Koruması"'
typeoutFallback: "Season"
heroButtons:
 - {link: "https://bit.ly/dfua-c4p", text: "Detailed Information"}
 - {permalink: "/#tickets", text: "Our Products"}
trHeroButtons:
 - {link: "https://bit.ly/dfua-c4p", text: "Detaylı Bilgi"}
 - {permalink: "/#tickets", text: "Çözümlerimiz"}

# About Block
aboutTitle: "With TR7"
aboutBlock:
 - {title: "Plug-and-Play", image: "plug.jpg", text: "TR7 is designed for companies that want a high-performance, uninterrupted plug-and-play system to balance application flows and guarantee the highest availability of critical application platforms / servers." }
 - {title: "Cost Effective", image: "money.jpg", text: "TR7 ASP, Open source components are optimized and used with reliable hardware platforms, provides business partners with advantageous prices at more competitive prices compared to other LB manufacturers." }
 - {title: "High Scalable", image: "scale.jpg", text: "With different boxes, it is adapted to every need with parallel operating modes (active-passive / active-active / passive-passive) depending on the processing power, infrastructure needs and critical level." }

# tr_About Block
tr_aboutTitle: "TR7 ile Güvenli Web Uygulamaları"
tr_aboutBlock:
 - {title: "Tak-Çalıştır", image: "plug.jpg", text: "TR7 uygulama akışlarını dengelemek ve kritik uygulama platformlarının / sunucularının en üst seviyede kullanılabilirliğini garanti etmek için, yüksek performanslı ve kesintiye uğramadan tak-çalıştır gibi bir sistem isteyen şirketler için tasarlanmıştır." }
 - {title: "Uygun Fiyat", image: "money.jpg", text: "TR7 TADP, Açık kaynak bileşenlerinin optimize edilerek, güvenilir donanım platformlarıyla birlikte kullanılması, TR7 TADP cihazlarının, LB/WAF sektöründeki en iyi performans / özellik / fiyat oranlarını sağlamaktadır. TR7 TADP, diğer LB üreticileri ile karşılaştırıldığında daha rekabetçi fiyatlarla iş ortaklarına avantajlı fiyatlar sağlamaktadır." }
 - {title: "Ölçeklenebilir", image: "scale.jpg", text: "Farklı kutularla, işlem gücü, altyapı ihtiyaçlarına ve kritiklik seviyesine bağlı olarak paralel çalışma modları (aktif-pasif / aktif-aktif / pasif-pasif) ile her ihtiyaca göre uyarlanır." }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "350", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "48", specialCharacter: "+", info: "hours", detail: "of pure Google technologies"}
 - {count: "20", specialCharacter: "+", info: "speakers", detail: "from country and beyond"}
 - {count: "3", specialCharacter: "", info: "parallel tracks", detail: "plus entertainment lounge"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4  
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Conference Hall"
eventLocationLink: "http://cabinet.kinopalace.lviv.ua/showtimes/"
eventStreetAddress: "22 Teatral'na St"
eventAddressLocality: "Lviv"
eventAddressLocalityRegion: "Lvivska"
eventPostalCode: "79000"
eventAddressCountry: "Ukraine"
eventStartTime: "2014-10-25T10:00"
eventDoorTime: "09:00"
eventEndTime: "2014-10-25T20:00"
eventPlaceCoordinates: "49.843237, 24.028751"
mapCenterCoordinates: "49.842537, 24.025701"
mapMobileCenterCoordinates: "49.841620, 24.029411"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Kinopalace Cinema"
venueFeatures: ["3 huge cinema screens", "Doulby Digital Surround EX audio system", "Located directly in the city center"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "devfest"
twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Pricetable"
ticketsInfo: "Tickets grant access to all conference sections, coffee brakes, lunch and party. Accommodation is NOT included in the ticket price."
ticketsOffers:
 -
  name: "Early Bird"
  price: "350"
  priceCurrency: "UAH"
  ticketsNumber: "150"
  ribbon: "-5%"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-25T10:00"
  validThrough: "2014-09-30T23:59"
 -
  name: "Last Chance"
  price: "450"
  priceCurrency: "UAH"
  ticketsNumber: "100"
  ribbon: "-20%"
  featured: true
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-10-01T00:00"
  validThrough: "2014-10-23T23:59"
  disabled: true
 -
  name: "Student"
  price: "200"
  priceCurrency: "UAH"
  ticketsNumber: "50"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-20T10:00"
  validThrough: "2014-10-23T23:59"
  soldOut: true
  soldOutText: "Sold Out"

# Footer
socialLinks:
 - {link: "https://www.linkedin.com/company/tr7-siber-savunma-a-ş/?viewAsMember=true", icon: "linkedin"}
 - {link: "https://twitter.com/siber_A", icon: "twitter"}
 - {link: "https://www.instagram.com/tr7_cybersecurity", icon: "instagram"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "/tr/", text: "Anasayfa"}
   - {link: "/tr/", text: "Online Demo"}
   - {link: "/tr/", text: "Poc Talebi"}
   - {link: "/tr/", text: "Siber Test"} 
 -
  title: "Contacts"
  links:
   - {link: "mailto:lviv@gdg.org.ua", text: "İş Ortakları"}
   - {link: "mailto:lviv@gdg.org.ua", text: "Blog"}
   - {link: "mailto:lviv@gdg.org.ua", text: "Dokümanlar"}

 
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "devfestua"

# TR Blog
trBlogTitle: "Türkçe Blog"
trBlogCommentsEnabled: true
trDiscusShortName: "devfestua"

# Speakers List Block
showSessions: false

# Team Block
teamBlockTitle: "Our History & Vision"
aboutUs: "As TR7 Cyber Security Inc., we set off to eliminate external dependency on load balancing, application distribution and application security, which is one of the areas where our country needs improvement in national cyber security, and to minimize the security gaps that may arise. With the prediction that international wars will take place with cyber elements instead of weapons, our work started in 2008 with producing domestic and national Load Balancer and Web Application Firewall as TRScaler and today continues with the addition of high performance and innovative features to our current technology with the TR7 brand name. "

# tr Team Block

tr_teamBlockTitle: "Geçmişimiz & Vizyonumuz"
aboutUs1: " TR7 Siber Savunma A.Ş. olarak, Ülkemizin milli siber güvenlik konusunda gelişime ihtiyaç duyulan alanlarından biri olan yük dengeleme, uygulama dağıtım ve uygulama güvenliği konularında dışa bağımlılığı ortadan kaldırıp, oluşabilecek güvenlik açıklarını en aza indirmeyi hedefleyerek yola çıktık. Uluslararası savaşların silahlar yerine siber unsurlar ile gerçekleşeceği öngörüsüyle, Türkiye'nin ilk yerli ve milli Yük Dengeleme ve Web Uygulama Güvenlik Duvarı ürünü olan TRScaler ile 2008 yılında başlayan çalışmalarımız, TR7 Markası ile yüksek performanslı ve yenilikçi özelliklerin mevcut teknolojimize sürekli eklenmesi ile devam etmektedir. "

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "0, 0"
logisticsMapMobileCenterCoordinates: "0, 0"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Lviv"
directionDetailsCards:
 - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
 - {title: "Public Transit", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
 - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Registration"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Attendance Details"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Solutions & Products
hackathonTitle: "Solutions & Products"
enableHackathon: true

# TR Solutions & Products
trHackathonTitle: "Çözümlerimiz ve Ürünlerimiz"
trEnableHackathon: true

# Solutions About Block
aboutHackathonTitle: "Secure your business with TR7"
hackathonRows:
 - {title: "Reliable Security", image: "securityicon.jpg", details: "Effective protection, learning and signature-based security with Positive and Negative WAF. Protocol authentication (HTTP) and full protection against denial of service attacks (DoS, DDoS), worms, SQL code injections, etc. Traffic manipulation and advanced URL filtering with authentication-based restriction capability."}
 - {title: "High Performance", image: "speed.png", details: "High speed caching system to free up your web servers and reduce page load times. Traffic compression and HTTP authentication/ authorization cache. TCP / HTTP acceleration through buffering and adjusting server link density with dynamic load balancing."}
 - {title: "Multilayer Load Balancing", image: "layers.png", details: "Load-Balancing supports different protocols (HTTP, DNS, SMTP, IMAP, POP3 etc.) for Layer3 and Layer7 load balancing. All IPv4 and IPv6 protocols, SNI-SSL based virtual hosts, content-based intelligent query routing (content change), reverse proxy, NAT, direct server converter and non-VIP modes are all supported."}

# tr Solutions About Block

tr_aboutHackathonTitle: "İşinizi TR7 ile güvence altına alın"
hackathonRows1:
 - {title: "Gelişmiş WAF Seçeneği", image: "securityicon.jpg", details: "Olumlu ve Olumsuz WAF ile etkili koruma, öğrenme ve imzaya dayalı güvenlik. Protokol kimlik doğrulaması (HTTP) ve hizmet reddi saldırılarına (DoS, DDoS), solucanlara, SQL kod enjeksiyonlarına vb. Karşı tam koruma. Kimlik doğrulama tabanlı kısıtlama özelliğine sahip trafik manipülasyonu ve gelişmiş URL filtreleme."}
 - {title: "Yüksek Performans", image: "speed.png", details: "Web sunucularınızı boşaltmak ve sayfa yükleme sürelerini azaltmak için yüksek hızlı önbelleğe alma sistemi. Trafik sıkıştırma ve HTTP kimlik doğrulama / yetkilendirme önbelleği. Dinamik yük dengeleme ile sunucu bağlantı yoğunluğunu arabelleğe alma ve ayarlama yoluyla TCP / HTTP hızlandırması."}
 - {title: "Multilayer Load Balancing", image: "layers.png", details: "Yük Dengeleme farklı protokolleri (HTTP, DNS, SMTP, IMAP, POP3 vb.) Destekler.) katman3 ve Katman 7 yük dengelemesi için. Tüm IPv4 ve IPv6 protokolleri, SNI-SSL tabanlı sanal konaklar, içerik tabanlı akıllı sorgu yönlendirme (içerik değiştirme), reverse proxy, NAT, doğrudan sunucu dönüştürücü ve VIP olmayan modların tümü desteklenir."}


# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
